### ISSUE TITLE
haskell_repl ignores aliases to haskell targets in experimental_from_*

### ISSUE THREAD

**Issue by jcpetruzza** [tweag/rules_haskell#993] opened 2019-07-12 14:06 UTC
**Describe the bug**
The `experimental_from_source` attribute of `haskell_repl()` will ignore aliases to haskell targets.

**To Reproduce**

From the following `BUILD.bazel`

```python
load("@io_tweag_rules_haskell//haskell:haskell.bzl", "haskell_repl")

alias(
  name = "foo",
  actual="//some/haskell/package",
)

haskell_repl(
  name="repl",
  deps=[":foo"],
  experimental_from_source=[":foo"]
)
```

We get:
```
bazel run :repl
INFO: Invocation ID: 180ff0c3-58df-4d91-989e-f53700b893a4
INFO: Analyzed target //bar:repl (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //bar:repl up-to-date:
  bazel-bin/bar/repl@repl
INFO: Elapsed time: 0.532s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 5 total actions
INFO: Build completed successfully, 5 total actions
GHCi, version 8.6.3: http://www.haskell.org/ghc/  :? for help
Ok, no modules loaded.
Ok, no modules loaded.
Loaded GHCi configuration from /home/daniel/.cache/bazel/_bazel_daniel/705e521ae91f78db4bc91d33cb5b8819/execroot/xxx/bazel-out/k8-fastbuild/bin/bar/ghci-repl-script-repl
Prelude> 
```

**Expected behavior**

ghci loads fine if I expand the alias of `foo` in `experimental_from_source` to:
```
 experimental_from_source=["//some/haskell/package"]
```
I expect the same to happen with an alias!

**Environment**
 - Ubuntu 18.04
 - Bazel version: 0.27
 - Version of the rules: 0.9.1

**Additional context**

We have a simple script that let us call `ghci` with an arbitrary set of our packages. This works by building a temporary `haskell_repl` target on the fly and calling `bazel run` on that. We are restricting the set of packages to those requested by the user or otherwise `ghci` may fail to build the code if one of the dependencies uses `NoImplicitPrelude` (this may be another issue in itself, but we haven't looked into it)

**Comment by aherrmann** [comment] 2019-07-15 08:40
@jcpetruzza Thanks for reporting this issue. I can reproduce this behavior.

Unfortunately, I don't think there's anything we can do about this. AFAIK Bazel doesn't offer any way to resolve aliases from within an aspect or rule implementation. Also note that the patterns provided in `experimental_from_source` and `experimental_from_binary` are simple strings and the pattern matching is implemented on strings. Bazel doesn't offer any way to hook into its builtin pattern matching, see https://github.com/bazelbuild/bazel/issues/7763.

I've checked which targets the aspect is executed on by adding a print statement [here](https://github.com/tweag/rules_haskell/blob/33acc8061f5c92e0b3f333ae868115ffbccf795c/haskell/repl.bzl#L313). It turns out that Bazel resolves aliases before executing aspects, meaning the aspect function never sees the alias target.

---

Regarding your use-case. At which stage are you generating the temporary `haskell_repl` target? If you have access to `bazel query`, you may be able to resolve aliases there, and pass the resolved target name to `experimental_from_source`.

Alternatively, you could blacklist the problematic targets by listing them in `experimental_from_binary`. You could also avoid having to generate the temporary `haskell_repl` target by defining a macro around `haskell_library` and `haskell_binary` that also generates corresponding `haskell_repl` targets.

**Comment by jcpetruzza** [comment] 2019-07-15 09:38
Thanks for looking into this, @aherrmann. I think I understand the problem and I'm also not aware of a way to normalize aliases in bazel.

In our script we are already issuing a `bazel query` to convert things like `:all` to haskell targets, so we'll have to do something similar for aliases, I guess.

**Comment by aherrmann** [comment] 2019-07-15 15:42
@jcpetruzza Thanks for understanding. I'm closing here. Feel free to reopen if you think there is a way that this can be addressed in rules_haskell.

**Closed by aherrmann** 2019-07-15 15:42 UTC
Labels: type: bug
