### ISSUE TITLE
How to bring up a REPL?

### ISSUE THREAD

**Issue by philderbeast** [tweag/rules_haskell#742] opened 2018-08-26 19:45 UTC
Please show how to bring up a REPL in the tutorial. From tweag/rules_haskell#380 it looks like I might be able to run a `-repl` target to do this.

The command to run as shown now in the readme;

```
rules_haskell_examples> bazel run @tutorial//main:demorgan
INFO: Analysed target @tutorial//main:demorgan (1 packages loaded).
INFO: Found 1 target...
Target @tutorial//main:demorgan up-to-date:
  bazel-bin/external/tutorial/main/demorgan
INFO: Elapsed time: 1.573s, Critical Path: 1.41s
INFO: 5 processes: 5 darwin-sandbox.
INFO: Build completed successfully, 9 total actions
INFO: Build completed successfully, 9 total actions
True
```

From the root folder, trying to run the `-repl` target;

```
rules_haskell_examples> bazel run @tutorial//main:demorgan-repl
INFO: Analysed target @tutorial//main:demorgan-repl (0 packages loaded).
INFO: Found 1 target...
Target @tutorial//main:demorgan-repl up-to-date:
  bazel-bin/external/tutorial/main/demorgan-repl
INFO: Elapsed time: 0.157s, Critical Path: 0.04s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/pdejoux/.ghci

<no location info>: error:
    can't find file: external/tutorial/main/Main.hs
Failed, no modules loaded.

<no location info>: error:
    Could not find module ‘Main’
    It is not a module in the current program, or in any known package.
Loaded GHCi configuration from bazel-out/darwin-fastbuild/bin/external/tutorial/main/ghci-repl-script-demorgan
Prelude> :q
Leaving GHCi.
```

From the tutorial folder, trying to run the `-repl` target;

```
rules_haskell_examples> cd tutorial
tutorial> bazel run //main:demorgan-repl
INFO: Analysed target //main:demorgan-repl (1 packages loaded).
INFO: Found 1 target...
Target //main:demorgan-repl up-to-date:
  bazel-bin/main/demorgan-repl
INFO: Elapsed time: 0.226s, Critical Path: 0.04s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/pdejoux/.ghci
[1 of 1] Compiling Main             ( main/Main.hs, interpreted )

main/Main.hs:5:1: error:
    Could not find module ‘Bool’
    Perhaps you haven't installed the "dyn" libraries for package ‘booleans-1.0.0’?
    Use -v to see a list of the files searched for.
  |
5 | import Bool
  | ^^^^^^^^^^^
Failed, no modules loaded.

<no location info>: error:
    Could not find module ‘Main’
    It is not a module in the current program, or in any known package.
Loaded GHCi configuration from bazel-out/darwin-fastbuild/bin/main/ghci-repl-script-demorgan
Prelude> :q
Leaving GHCi.
```

**Comment by mboes** [comment] 2019-03-13 09:08
@Profpatsch ok so is there anything left here to do that isn't a dupe of #348?

**Comment by Profpatsch** [comment] 2019-03-13 11:05
Actually all of that should be fixed by https://github.com/tweag/rules_haskell/pull/736, according to Andreas.

**Closed** 2019-08-11 12:25 UTC
