### ISSUE TITLE
No link to anything from `base` when using `haskell_doc`

### ISSUE THREAD

**Issue by gdeest** [tweag/rules_haskell#230] opened 2018-05-02 15:55 UTC
It looks like Haddock fails to generate hyperlinks to documentation for anything in `base` when invoked via an `haskell_doc` incantation, also triggering a lot of warnings.

**Comment by mrkkrp** [comment] 2018-05-03 09:05
Mostly a dupe of #53.

**Closed** 2018-05-03 16:41 UTC
