### ISSUE TITLE
Can't build anything depending on `haddock-library` (for whatever reason)

### ISSUE THREAD

**Issue by neongreen** [tweag/rules_haskell#208] opened 2018-04-09 22:53 UTC
I'm trying to bazel-ify Pandoc. You can find my repository here: https://github.com/neongreen/bazel-pandoc.

I have found that importing anything from [`haddock-library`](https://hackage.haskell.org/package/haddock-library) doesn't work. Specifically:

```
[ 48 of 131] Compiling Text.Pandoc.Readers.Haddock ( src/Text/Pandoc/Readers/Haddock.hs, bazel-out/k8-fastbuild/bin/objects-pandoc-1.0.0/Text/Pandoc/Readers/Haddock.o )

src/Text/Pandoc/Readers/Haddock.hs:22:1: error:
    Could not find module `Documentation.Haddock.Parser'
    Use -v to see a list of the files searched for.
   |
22 | import Documentation.Haddock.Parser
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Text/Pandoc/Readers/Haddock.hs:23:1: error:
    Could not find module `Documentation.Haddock.Types'
    Use -v to see a list of the files searched for.
   |
23 | import Documentation.Haddock.Types
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO: Elapsed time: 19.325s, Critical Path: 18.70s
FAILED: Build did NOT complete successfully
```

I feel that this might be somehow related to the fact that I'm getting warnings mentioning `haddock-library` during the phase when dependencies are downloaded by Nix:

```
propagated-build-inputs: /nix/store/71hqp0pa12x1g920agfwrf9zlv0iff9d-x509-system-1.6.6/nix-support/propagated-build-inputs
/nix/store/2pdyyxb4dzhrbpyhq57rwnn8nahahr9f-ghc-8.2.2/nix-support:
propagated-build-inputs: /nix/store/71hqp0pa12x1g920agfwrf9zlv0iff9d-x509-system-1.6.6/nix-support/propagated-build-inputs
Warning: haddock-interfaces: /nix/store/f6qlkbggjw2qbnc5vqnvdkw0ah3j08k1-haddock-library-1.4.5/share/doc/x86_64-linux-ghc-8.2.2/had
dock-library-1.4.5/html/haddock-library.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/f6qlkbggjw2qbnc5vqnvdkw0ah3j08k1-haddock-library-1.4.5/share/doc/x86_64-linux-ghc-8.2.2/haddock-l
ibrary-1.4.5/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /nix/store/f6qlkbggjw2qbnc5vqnvdkw0ah3j08k1-haddock-library-1.4.5/share/doc/x86_64-linux-ghc-8.2.2/had
dock-library-1.4.5/html/haddock-library.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/f6qlkbggjw2qbnc5vqnvdkw0ah3j08k1-haddock-library-1.4.5/share/doc/x86_64-linux-ghc-8.2.2/haddock-l
ibrary-1.4.5/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /nix/store/kaq5b27dq5gb506siqchjm7ypx8pbhhd-JuicyPixels-3.2.9.5/share/doc/x86_64-linux-ghc-8.2.2/Juicy
Pixels-3.2.9.5/html/JuicyPixels.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/kaq5b27dq5gb506siqchjm7ypx8pbhhd-JuicyPixels-3.2.9.5/share/doc/x86_64-linux-ghc-8.2.2/JuicyPixels
-3.2.9.5/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /nix/store/llfjyn78rvk36vs49wppdvi5059nf7d9-fail-4.9.0.0/share/doc/x86_64-linux-ghc-8.2.2/fail-4.9.0.0
/html/fail.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/llfjyn78rvk36vs49wppdvi5059nf7d9-fail-4.9.0.0/share/doc/x86_64-linux-ghc-8.2.2/fail-4.9.0.0/html
doesn't exist or isn't a directory
/nix/store/m6jxpqy6c78wncrd4jhcmikv7r3bh6dc-ghc-8.2.2-with-packages
INFO: Analysed 3 targets (4 packages loaded).
INFO: Found 3 targets...
```

**Comment by mrkkrp** [comment] 2018-04-11 13:09
I don’t think so. #172 is about building docs, while this one is about building actual code (Pandoc library).

**Comment by mrkkrp** [comment] 2018-04-20 08:11
@neongreen Can you confirm that the problem is resolved if you use the latest version of the code? If so, please close the issue.

**Comment by mrkkrp** [comment] 2018-05-02 12:44
Closing due to lack of reply. Re-open if necessary.

**Closed by mrkkrp** 2018-05-02 12:44 UTC
