### ISSUE TITLE
`dns-internal -any` internal library not visible from rules_haskell

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1439] opened 2020-11-09 09:47 UTC
**Describe the bug**

I am trying to build https://hackage.haskell.org/package/dns via a stack_snapshot but it fails with 
```
A clear and concise description of what the bug is.
bazel build @hackage//:dns
INFO: Invocation ID: 0bc6895d-90fe-4520-9ced-ec6fe4302334
INFO: Analyzed target @hackage//:dns (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/teto/.cache/bazel/_bazel_teto/f3097620197e6c203645e1230d1ae88c/external/hackage/BUILD.bazel:1696:22: HaskellCabalLibrary @hackage//:dns failed (Exit 1) cabal_wrapper failed: error executing command bazel-out/k8-fastbuild/bin/external/rules_haskell/haskell/cabal_wrapper lib:dns dns-4.0.1 true external/hackage/dns-4.0.1/Setup.hs external/hackage/dns-4.0.1 ... (remaining 27 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Setup.hs: Encountered missing or private dependencies:
dns-internal -any
```

dns-internal is defined within the dns package https://github.com/kazu-yamamoto/dns/blob/master/dns.cabal#L23 : what's the best way to deal with this with rules_haskell ?

**Environment**
 - OS name + version: nixos-unstable
 - Bazel version: >3
 - Version of the rules: current master

**Additional context**
This happens while trying to build https://hackage.haskell.org/package/mongoDB with ghc 8.8.4.

**Comment by Profpatsch** [comment] 2020-11-09 14:08
Named/internal libraries were only added to cabal a short while ago iirc; do we know what changes we need to do to the `Setup.hs` compilation/call to also support these?

**Comment by aherrmann** [comment] 2020-11-09 14:59
The Cabal rules `haskell_cabal_library` and `haskell_cabal_binary` each build only a [specific cabal component](https://github.com/tweag/rules_haskell/blob/6ad9e2b336d24e311137234f2315d593ca4a1c77/haskell/cabal.bzl#L416-L418). For a library that is `lib:<package-name>`. I assume if we pointed that to `lib:dns-internal` then it would build the internal library that's missing in this case.

The package name is also used to [determine the package-id](https://github.com/tweag/rules_haskell/blob/6ad9e2b336d24e311137234f2315d593ca4a1c77/haskell/cabal.bzl#L345-L348) and the output paths. What package-id does Cabal assign to internal libraries?

> what's the best way to deal with this with rules_haskell ?

As @Profpatsch points out internal libraries are a very recent feature that is not currently supported by rules_haskell.

For testing and development purposes it would be easiest to vendor the package and inject it into stack_snapshot using the [vendored_packages](https://api.haskell.build/haskell/cabal.html#stack_snapshot-vendored_packages) attribute. An example is available [here](https://github.com/tweag/rules_haskell/blob/6ad9e2b336d24e311137234f2315d593ca4a1c77/examples/WORKSPACE#L66-L116).

Once `haskell_cabal_library` can handle such internal libraries we'd also want to add support to `stack_snapshot` directly and extend it's handling of [package components](https://github.com/tweag/rules_haskell/blob/6ad9e2b336d24e311137234f2315d593ca4a1c77/haskell/cabal.bzl#L912). One difficulty here are dependencies between multiple sub-libraries of a package. As of now `stack` [does not expose information about Cabal components](https://github.com/commercialhaskell/stack/issues/5275).

**Comment by lunaris** [comment] 2021-02-19 16:39
In case it's helpful, I ran up against this and, for the `dns` package specifically, took the approach of patching the Cabal file to get rid of the internal library (disclaimer: hacks incoming):

```diff
diff --git a/dns.cabal b/dns.cabal
index 6e08e8e..d47c3f6 100644
--- a/dns.cabal
+++ b/dns.cabal
@@ -20,43 +20,11 @@ Tested-With:            GHC == 8.0.2
                       , GHC == 8.6.5
                       , GHC == 8.8.1

-Library dns-internal
-  Default-Language:     Haskell2010
-  GHC-Options:          -Wall
-  Hs-Source-Dirs:       internal
-  Exposed-Modules:      Network.DNS.Imports
-                        Network.DNS.Types.Internal
-                        Network.DNS.Types.Resolver
-                        Network.DNS.Resolver.Internal
-                        Network.DNS.Decode.Parsers
-                        Network.DNS.Decode.Internal
-                        Network.DNS.Encode.Builders
-                        Network.DNS.Encode.Internal
-                        Network.DNS.StateBinary
-                        Network.DNS.Memo
-                        Network.DNS.Base32Hex
-  Build-Depends:        base
-                      , array
-                      , async
-                      , attoparsec
-                      , auto-update
-                      , base16-bytestring
-                      , base64-bytestring
-                      , bytestring
-                      , containers
-                      , cryptonite
-                      , hourglass
-                      , iproute
-                      , mtl
-                      , network
-                      , psqueues
-  if os(windows)
-    C-Sources:        cbits/dns.c
-    Extra-Libraries:  iphlpapi
-
 Library
   Default-Language:     Haskell2010
   GHC-Options:          -Wall
+  Hs-Source-Dirs:       .
+                        internal
   Exposed-Modules:      Network.DNS
                         Network.DNS.Lookup
                         Network.DNS.LookupRaw
@@ -67,8 +35,20 @@ Library
                         Network.DNS.Encode
                         Network.DNS.IO
   Other-Modules:        Network.DNS.Transport
-  Build-Depends:        dns-internal
-                      , base >= 4 && < 5
+
+                        Network.DNS.Imports
+                        Network.DNS.Types.Internal
+                        Network.DNS.Types.Resolver
+                        Network.DNS.Resolver.Internal
+                        Network.DNS.Decode.Parsers
+                        Network.DNS.Decode.Internal
+                        Network.DNS.Encode.Builders
+                        Network.DNS.Encode.Internal
+                        Network.DNS.StateBinary
+                        Network.DNS.Memo
+                        Network.DNS.Base32Hex
+
+  Build-Depends:        base >= 4 && < 5
                       , array
                       , async
                       , attoparsec
@@ -83,6 +63,9 @@ Library
                       , mtl
                       , network >= 2.3
                       , psqueues
+  if os(windows)
+    C-Sources:        cbits/dns.c
+    Extra-Libraries:  iphlpapi

 Test-Suite network-tests
   Type:                 exitcode-stdio-1.0
```

You can use this e.g. with `http_archive` 's `patches` attribute to patch the source before injecting `BUILD.bazel` content containing a `haskell_cabal_library` call (similar to Andreas' linked example above). Before resorting to this I tried injecting `BUILD.bazel` content using two calls to `haskell_cabal_library`, one for `dns` and one for `dns-internal`, but I think `haskell_cabal_library` will need some tweaking as suggested, as I get the dreaded `output 'external/hs-dns/_install/lib/libHSdns-internal-4.0.1.a' was not created` errors, etc.

**Comment by brendanhay** [comment] 2022-01-26 08:51
This is now happening for `attoparsec == 0.14.4`, which f.e. is contained within the latest `stack_snapshot.snapshot = "nightly-2022-01-26"`:

```
$ bazel build @stackage//:attoparsec
...
Setup.lhs: Encountered missing or private dependencies:
attoparsec:attoparsec-internal
```

(Using `rules_haskell` 156b091fc1b8d0736ad9f072cdc9abdadacbf57f)

**Comment by aherrmann** [comment] 2022-01-26 08:57
@ylecornec With #1555 merged, is there a good way to fix this issue?

**Comment by ylecornec** [comment] 2022-01-26 10:14
Indeed the main `attoparsec` library now depend on the `attoparsec-internal` sublibrary ([here is the cabal file](https://github.com/haskell/attoparsec/blob/master/attoparsec.cabal#L37-L64)).

As mentioned above, we do not read the `.cabal` file ourselves (and rely on stack). This means we need to manually declare this sublibrary in the `stack_snapshot`rule and specify that the main library (`lib:attoparsec`) depends on it.

I did not test it yet but adding the following attributes to the `stack_snapshot` rule should work:

```
stack_snapshot(
    ...,

    components = {
        "attoparsec": [
            "lib:attoparsec",
            "lib:attoparsec-internal",
        ],
    },
    components_dependencies = {
        "attoparsec": """{"lib:attoparsec": ["lib:attoparsec-internal"]}""",
    },
)
```

There is an example of this [here](https://github.com/tweag/rules_haskell/blob/master/WORKSPACE#L117-L125).

**Comment by brendanhay** [comment] 2022-01-26 12:02
Adding the attributes works as advertised, thanks @ylecornec!

**Comment by aherrmann** [comment] 2022-01-26 13:33
Thank you @ylecornec! And great to hear that it's working @brendanhay!
Sounds like the issue is resolved, correct?
I'll close it. Feel free to reopen if you feel there's something still missing.

**Closed by aherrmann** 2022-01-26 13:33 UTC
Labels: type: feature request, type: bug

**Comment by cocreature** [comment] 2022-01-26 18:40
Is there a chance of automatically generating these sections? Right now it’s only attoparsec this could get out of hand at some point as internal libraries start being used more. And having to worry about internal libraries also seems to somewhat go against the idea of them being internal.

**Comment by aherrmann** [comment] 2022-01-27 08:29
We're relying on `stack ls dependencies json` for the version and dependency information. Right now stack does not expose package components. If it did, and also exposed the inter-component dependency graph, then we could autogenerate these entries. See https://github.com/commercialhaskell/stack/issues/5275.
