### ISSUE TITLE
ghcide doesn't work on latest master

### ISSUE THREAD

**Issue by regnat** [tweag/rules_haskell#1346] opened 2020-05-28 12:27 UTC
**Describe the bug**

Since 844f87f5965fbf000faeeccab13e312672d0a932 running ghcide fails with 

```
ghcide: target ‘"-pgma"’ is not a module name or a source file
```

**To Reproduce**

```sh
git checkout ghcide-ghc8.8 # ghcide branch rebased on top of master and with an updated ghcide stackage snapshot to build on top of ghc8.8
./.ghcide tests/binary-custom-main/Main.hs # Run ghcide on a random file
```

**Expected behavior**

The command should return without any error

**Environment**
 - OS name + version:
 - Bazel version:
 - Version of the rules: 844f87f5965fbf000faeeccab13e312672d0a932

**Additional context**

`./.hie-bios` prints some quoted flags which are taken litterally by ghcide.
Crudely removing the quotes in the script removes the error (see the diff below)

```diff
diff --git a/.hie-bios b/.hie-bios
index 31f3736a..2cd6becf 100755
--- a/.hie-bios
+++ b/.hie-bios
@@ -15,7 +15,8 @@ hie_bios_flags() {
       {
         print $0 > "/dev/stderr"
       }
-    '
+    ' \
+    | sed 's/"//g'
   # Make warnings non-fatal
   echo -Wwarn
 }
```

**Comment by hanshoglund** [comment] 2020-06-22 15:34
I can't reproduce this in master using Nixpkgs.

I've attempted a CI reproduction here: https://github.com/tweag/rules_haskell/pull/1375

**Comment by aherrmann** [comment] 2020-06-22 15:53
This was fixed in https://github.com/tweag/rules_haskell/pull/1262/commits/da560fd41428b0bdfbc4c444c45779934437cd92 as part of #1262. Sorry, I forgot to close this issue afterwards.

**Closed by aherrmann** 2020-06-22 15:53 UTC
Labels: type: bug
