### ISSUE TITLE
Test Hazel on rules_haskell

### ISSUE THREAD

**Issue by nmattia** [tweag/rules_haskell#703] opened 2019-02-13 14:21 UTC
We want to use hazel for building Haskell dependencies on both Windows and Linux. The Hazel mechanism should be tested inside rules_haskell. This means:
* Add a "hackage"-like repository using Hazel in rules_haskell
* Port as many tests as possible to use the new mechanism, especially when using the GHC bindist platform
* Turn on all the working tests on bindist and Windows platforms

It is currently unclear how Hazel will be called from rules_haskell. At first we can simply pull a recent Hazel commit from rules_haskell. In the longer this will get tricky as both rules_haskell and Hazel cannot depend on each other's latest commit at the same time.

**Comment by mboes** [comment] 2019-02-19 08:17
> It is currently unclear how Hazel will be called from rules_haskell. At first we can simply pull a recent Hazel commit from rules_haskell. In the longer this will get tricky as both rules_haskell and Hazel cannot depend on each other's latest commit at the same time.

The crux of the problem is that Hazel is a downstream dependency. As such, tests should not happen here but should happen downstream. If you believe that Hazel and rules_haskell are too closely interlinked, then that means that should be a single project, not two. See @int-index's [recent plea](https://mail.haskell.org/pipermail/ghc-devs/2019-February/017120.html) to combine all SCC's (strongly connected components) in a single repo in GHC.

There was a ticket already about possibly merging Hazel and rules_haskell, but I can't find it now. Will keep looking...

**Comment by mboes** [comment] 2019-02-19 08:20
Ah. [Here](https://github.com/tweag/rules_haskell/issues/357#issuecomment-408159750) and the ensuing discussion. This should be turned into a ticket.

**Comment by nmattia** [comment] 2019-02-19 13:13
Yes, and as mentioned somewhere else:

> I'm thinking about the interface between rules_haskell and hazel. rules_haskell aims at building haskell packages generally, that is not only GHC core packages (bytestring, etc) and standalone packages (with no dependencies) but also real world Haskell project that depend on other haskell libraries. The way rules_haskell deals with this currently is by using nixpkgs.
Using nixpkgs meant that we could focus on developing a framework for building haskell packages one at a time, without having to care about dependencies. rules_haskell is now pretty good at building single packages. however it depends on a third-party package manager, nixpkgs, for pulling haskell dependencies. I think this should be taken care of by Bazel itself.
I suggest either incorporating Hazel in the rules_haskell repo, or coming up with an equivalent solution, so that we can use bazel to build full-blown haskell packages, including dependencies.

Note also that there is currently some impedance mismatch, see https://github.com/FormationAI/hazel/issues/78 . Figuring out how to port Hazel to rules_haskell and performing that work will take some time, more that I had originally anticipated for this ticket (#703). I'll unassign myself for now.

**Comment by Profpatsch** [comment] 2019-02-21 12:20
Closing in favor of https://github.com/tweag/rules_haskell/issues/716

**Closed by Profpatsch** 2019-02-21 12:20 UTC
