### ISSUE TITLE
Startup script: version bound check is not precise enough

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#972] opened 2019-06-28 14:01 UTC
When running the `start.sh` script, a lower bound is checked on Bazel. But that's not precise enough in practice. I've experienced that this morning, where my Bazel version was too recent for the versions pointed by the `start.sh` script. (This is tangentially related t #741 )

Let's face it: Bazel changes too fast to promise that a version of rules_haskell works even with two consecutive versions. So let's be prescriptive, and make it so that the start script _prescribes one precise version_ of Bazel, and refuses to work otherwise (you may add a jailbreak button somewhere for the expert, but for the uninitiated, it's too much to deal with).

Because we are very much supporting Bazel being installed by nixpkgs, this means that the startup script should also give, in case of version mismatch, the user a version of nixpkgs where the proper Bazel is installed (it can be the same version pinned in the rules_haskell repository, this would make a lot of sense).

**Comment by mboes** [comment] 2019-06-28 15:42
Dupe of #923, a P1 priority feature request.

**Closed by mboes** 2019-06-28 15:42 UTC
Labels: type: bug
