### ISSUE TITLE
GCP remote build execution

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#940] opened 2019-06-12 19:05 UTC
Is RBE support on your roadmap? What needs to be done to add support for it?

**Comment by Profpatsch** [comment] 2019-06-13 14:03
Yes, and we are actively in conversation with the RBE team to push them towards goods support of `rules_haskell`. cc @mboes

**Comment by mboes** [comment] 2019-06-13 16:09
This is on the roadmap. And yes we are discussing with the RBE team, but this is not a blocker for rules_haskell on RBE by any means. The work necessary isn't huge, it just hasn't been prioritized, for lack of demand.

We need:

- a new workspace rule to use a non-Bazel provided GHC toolchain (the current bindist rule won't work due to RBE restrictions and poor design of the bindists provided by upstream).
- a custom Docker image that includes GHC as a toolchain, like the stock ones include GCC/Clang, OpenJDK etc.
- testing and benchmarking.

**Comment by ghorn** [comment] 2019-06-13 19:50
We currently get GHC toolchain and many third party libraries from nix. Will the Docker image be compatible with this? When we edit our nix dependencies, will we need to manually create a new Docker image?

**Comment by mboes** [comment] 2019-06-18 22:18
Yes, that's fine. We can generate the Docker image from the Nix dependencies. You will have to recreate them every time the Nix dependencies change, but that's also the workflow even without using Nix, and should be workable for now. As I said, maybe we can convince Google to enable better workflows, but that's not going to happen straight away.

**Comment by aherrmann** [comment] 2022-02-16 10:24
Closing as duplicate of https://github.com/tweag/rules_haskell/issues/1322 and https://github.com/tweag/rules_haskell/issues/1321.

**Closed by aherrmann** 2022-02-16 10:24 UTC
Labels: type: feature request
