### ISSUE TITLE
Non reproducible manifest

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1126] opened 2019-10-16 18:53 UTC
**Describe the bug**

The content of manifest generated by rules Haskell is not reproducible.

This technically leads to different input for all of the Haskell rules hence more unnecessary rebuilds and more cache misses.

**To Reproduce**

That's a bit tricky. I'm just explaining the reason.

We use `find` in a few places to list files (such as `.o` files). `find` will return files in an order which is unspecified and depends mostly on the underlying file system implementation and the history of file creation / modifications. See for yourself:

```
λ paddle test_dir → ls                                                                                                                                                                                               ~/test_dir
λ paddle test_dir → touch a b c                                                                                                                                                                                      ~/test_dir
λ paddle test_dir → find                                                                                                                                                                                             ~/test_dir
.
./a
./b
./c
λ paddle test_dir → rm a                                                                                                                                                                                             ~/test_dir
λ paddle test_dir → touch a                                                                                                                                                                                          ~/test_dir
λ paddle test_dir → find                                                                                                                                                                                             ~/test_dir
.
./b
./c
./a
```

**Expected behavior**

I propose to pipe the output of all these command to `sort`.

I'll soon open a PR with a solution.

**Comment by guibou** [comment] 2019-10-17 15:10
@Profpatsch Should we schedule an important release for this issue now that #1128 is merged?

Rules haskell main (if only) selling points are that it is reproducible and fast (thank to bazel caching).

Due to this issue, rules haskell was not reproducible (the order of files in the manifest influence the resulting binary) and not fast (because bazel caching was not working).

**Comment by Profpatsch** [comment] 2019-10-17 16:14
I wanted to make a point-release anyway (to support 1.0). We should do that.

**Comment by aherrmann** [comment] 2019-10-17 17:26
#1128 was merged but didn't auto close this. Closing manually.

**Closed by aherrmann** 2019-10-17 17:26 UTC
Labels: P0, type: bug

**Comment by mboes** [comment] 2019-10-20 08:02
@guibou let's use more precise terms than "reproducibility". A build is reproducible if it is hermetic and deterministic. The problem here is non-determinism specifically. It's been present in the rules_haskell codebase since August 2018, so over a year. Clearly, it hasn't been a blocker for anyone in all this time, or we would have noticed it sooner. So the P0 "blocker: fix immediately!" priority label and a request for an immediate new release seems excessive to me, even if I'm happy to see that we managed to fix this in short order.

Note also that in this instance, the non-determinism is due to the result of some filesystem related syscalls (`readdir(2)` in particular) being non-deterministic. Even build actions in a Nix sandbox can exhibit the same problem. We must be careful to make all I/O deterministic, but no system provides the *guarantee* that all I/O by all build actions is deterministic. This state of affairs is a tad unfortunate, but let's be clear: the non-determinism here degrades our cache hit rates, but it's not making builds randomly fail when they otherwise succeed (on a different machine, or on the same machine at a different time).  By the way, GHC itself is plagued with non-deterministic output. It's occasionally a problem for Nix and Bazel users alike, and has been so for years. It's a problem worth fixing, but not dropping everything else to fix immediately or else.
