### ISSUE TITLE
Test multiple GHC versions/configurations on CI

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#1403] opened 2020-07-28 14:37 UTC
**Is your feature request related to a problem? Please describe.**
rules_haskell can be used with different GHC versions and GHC in different configurations. However, CI currently only tests GHC 8.8 provided by GHC bindist or nixpkgs on Linux and MacOS and GHC 8.6 provided by bindist on Windows. That means that some versions are untested, e.g. 8.6 or 8.10 on Unix. It also leaves some configurations untested, e.g. GHC with static RTS or GHC with fully static linking as is supported.

**Describe the solution you'd like**
We should test the versions and configurations of GHC that we consider supported on CI.

**Additional context**
This is related to https://github.com/tweag/rules_haskell/issues/1402 in that the CI setup for multiple GHC versions and configurations may be similar to that for multiple Bazel versions.

**Comment by Xophmeister** [comment] 2022-02-21 11:37
#1668 is effectively a duplicate of this

**Comment by GuillaumeGen** [comment] 2022-07-26 15:57
Duplicate of #458

**Closed by GuillaumeGen** 2022-07-26 15:57 UTC
Labels: type: feature request, P2
