### ISSUE TITLE
Haddock does not create hyperlinks to things coming from pre-built dependencies

### ISSUE THREAD

**Issue by mrkkrp** [tweag/rules_haskell#125] opened 2018-02-11 10:25 UTC
While working on #124, I noticed that `haskell_doc` does not generate links to things from pre-built dependencies such as `base`. For example, in one of our tests, no link to `Int` is created. This sucks.

I checked what Cabal does and it looks like we must pass `--read-interface` arguments even for pre-built dependencies because Haddock cannot figure out this on its own (I confirmed that this works).

So we need to find out locations of HTML directory and Haddock interface file for pre-built library X. This can be done on the command line like this:

```
[mark@arch ~]$ ghc-pkg field base haddock-interfaces
haddock-interfaces: /usr/share/doc/ghc/html/libraries/base-4.10.1.0/base.haddock
[mark@arch ~]$ ghc-pkg field base haddock-html
haddock-html: /usr/share/doc/ghc/html/libraries/base-4.10.1.0
```

The problem, of course, is that it's not possible to grab output of shell commands in rule implementations, and that's intentional afaicu. I'm not sure yet what is the correct way to make it work.

**Comment by Fuuzetsu** [comment] 2018-02-11 11:13
This is a duplicate of #52.

**Closed** 2018-02-11 11:15 UTC

**Comment by Fuuzetsu** [comment] 2018-02-11 11:17
>The problem, of course, is that it's not possible to grab output of shell commands in rule implementations

The bash hack we used elsewhere would let you inline ghc-pkg calls but that sucks. An alernative is a rule step that calls it for every target and outputs the flags into a file. I think you can add a file into `args` as a response file. Both ways kind of suck but it should be doable.

**Comment by Fuuzetsu** [comment] 2018-02-11 11:19
Seems second half of my comment is incorrect.
