### ISSUE TITLE
use local packages in snapshot.yml

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1525] opened 2021-04-02 15:27 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to update our ghc version to 8.10.4. As usual some packages dont support the platform yet so I am patching them.
To speed up the testing workflow, I tried to use local packages in my snapshot.yaml instead of github repositories to avoid having to update the `commit` bit (i.e., git revision).
```
resolver: lts-17.8

# - local-package
# - location: vendor/binary
packages:
  - /home/teto/streaming-conduit
```

I suppose it fails for good reasons (not reproducible) but I wonder if I could hack my way around ?
```
bazel build //... ; noti
INFO: Invocation ID: f98a3dfb-de70-47cc-9bd6-986f5be239b7
INFO: Repository hackage instantiated at:
  /home/teto/nova/jinko3/WORKSPACE:55:20: in <toplevel>
  /home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/buildlib/haskell.bzl:117:19: in jinko_haskell_setup
  /home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/rules_haskell/haskell/cabal.bzl:2374:20: in stack_snapshot
Repository rule _stack_snapshot defined at:
  /home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/rules_haskell/haskell/cabal.bzl:2027:34: in <toplevel>
ERROR: An error occurred during the fetch of repository 'hackage':
   Traceback (most recent call last):
	File "/home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/rules_haskell/haskell/cabal.bzl", line 1829, column 37, in _stack_snapshot_impl
		resolved = _resolve_packages(
	File "/home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/rules_haskell/haskell/cabal.bzl", line 1256, column 42, in _resolve_packages
		exec_result = _execute_or_fail_loudly(
	File "/home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/rules_haskell/haskell/private/workspace_utils.bzl", line 27, column 13, in execute_or_fail_loudly
		fail("\n".join(["Command failed: " + " ".join(arguments), exec_result.stderr]))
Error in fail: Command failed: /home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/rules_haskell_stack/stack ls dependencies json --global-hints --external
Exception while reading snapshot from /home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/buildlib/hackage/snapshot.yaml:
Couldn't parse snapshot from /home/teto/.cache/bazel/_bazel_teto/b25a84786e6d9b137eae45b9dec297ea/external/buildlib/hackage/snapshot.yaml: Error in $.packages[8]: failed to parse field 'packages': Could not parse a UnresolvedRawPackageLocationImmutable from: String "/home/teto/nova/streaming-conduit"
```

**Describe the solution you'd like**
toggle some flags/ add the folder to sandbox  ot make it work.

**Describe alternatives you've considered**
Upload the code to github forks and use those instead. Doable but increase the test loop.

It's fine if it's not supported, I can see why. I can also work around but it's a bit more painful xD

**Comment by ak3n** [comment] 2021-04-12 11:26
Unfortunately, snapshots do not support local directories to ensure reproducibility (https://github.com/commercialhaskell/stack/blob/master/doc/pantry.md#snapshots).

**Comment by aherrmann** [comment] 2021-04-12 14:16
As @ak3n points out stack custom snapshots don't support local packages.

With Bazel this is already supported. You can use [`new_local_repository`](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository) to include `/home/teto/streaming-conduit` as a Bazel workspace and set the `build_file` or `build_file_content` attribute to define a `haskell_cabal_library` rule similar to [here](https://github.com/tweag/rules_haskell/blob/a757876f43583dad6301e06da11d4f38bde8ac80/examples/WORKSPACE#L69-L79). Then you can use the [`vendored_packages`](https://api.haskell.build/haskell/cabal.html#stack_snapshot-vendored_packages) attribute to include the package into the Bazel built stack snapshot.

Closing as `snapshot.yml` itself is controlled by stack and thereby out of scope for rules_haskell, and since the use-case is supported using `vendored_packages` and `new_local_repository`. @teto feel free to reopen if you feel this is insufficient.

**Closed by aherrmann** 2021-04-12 14:16 UTC
Labels: type: feature request

**Comment by teto** [comment] 2021-04-12 22:41
no pb, that's  what I was expecting. I was just looking for an escape hatch  and you just gave one to me thanks. Might be good adding to faq

**Comment by aherrmann** [comment] 2021-04-16 14:56
> Might be good adding to faq

Good idea, I've opened https://github.com/tweag/rules_haskell/pull/1544 which extends the use-case docs for `stack_snapshot`.
