### ISSUE TITLE
data-files are not found in TH

### ISSUE THREAD

**Issue by cocreature** [tweag/rules_haskell#1246] opened 2020-02-18 16:23 UTC
**Describe the bug**

If you try to locate `data-files` from a dependency in TH, they won’t be found. The reason for that is that the `Paths_` modules generated look something like

```
getDataDir = catchIO (getEnv "js_jquery_datadir") (\_ -> getPrefixDirReloc "js-jquery-3.3.1_data")
```
`getPrefixDirReloc` is relative to `getExecutableName` which in TH points to `GHC`. This leads to errors like

```
Exception when trying to run compile-time code:
        /nix/store/ffnk6gg2pbdbv7618cgjj4yfd5xxvi3j-ghc-8.6.5/lib/ghc-8.6.5/js-jquery-3.3.1_data/jquery-3.3.1.min.js: openBinaryFile: does not exist (No such file or directory)
```

**To Reproduce**

Building `@stackage//:shake` with the `embed-files` flag set to `True` surfaces this issue. Needs a sufficiently recent version of `shake`. I tested with `0.18.5`.

**Expected behavior**

`shake` should build successfully.

**Environment**
 - Version of the rules: 1fedad7e64ea00ecf1bcb4be70ca51a11dc48312

Given that the `Paths_` files do seem to check for an environment variable first, it might be possible to set this during compilation for all dependencies to work around this.

**Comment by aherrmann** [comment] 2020-02-19 17:32
I was able to reproduce this with `Cabal` outside of Bazel. I've raised an issue upstream: https://github.com/haskell/cabal/issues/6549

**Comment by mboes** [comment] 2020-02-19 18:25
Shall we close this one then?

**Comment by cocreature** [comment] 2020-02-19 19:26
I think in theory, `rules_haskell` could work around this by setting the environment variables. Not sure whether it’s worth doing. In `daml`, I’ve just patched Shake and the corresponding dependencies to use `file-embed` everywhere.

**Comment by aherrmann** [comment] 2020-02-20 09:26
> I think in theory, `rules_haskell` could work around this by setting the environment variables. Not sure whether it’s worth doing.

That's true, though I'd prefer not to spam the build with that many environment variables if it can be avoided. It sounds like this might be fixed in Cabal in the not too distant future. So, I don't think working around this in `rules_haskell` is worth it now.

I'll close this for now. If it becomes an issue again and a fix in upstream turns out to be further away then we can still add a workaround in `rules_haskell`.

**Closed by aherrmann** 2020-02-20 09:26 UTC
Labels: type: bug

**Comment by mboes** [comment] 2020-02-20 15:50
:+1: to what @aherrmann says above. I want to set a high bar for changing things in the core rules_haskell rules only for the benefit of Cabal.
