### ISSUE TITLE
@repl targets incompatible with --nobuild_runfile_links

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1476] opened 2021-01-27 19:09 UTC
**Describe the bug**

`bazel run --nobuild_runfile_links //an/haskell/repl` fails.

**To Reproduce**

On current rules_haskell repository (i.e. `bf28f164772c2e70f4f64509006eb4f488f56681`):

```
bazel run --nobuild_runfile_links //tests/multi_repl/a:a@repl
INFO: Analyzed target //tests/multi_repl/a:a@repl (51 packages loaded, 1094 targets configured).
INFO: Found 1 target...
Target //tests/multi_repl/a:a@repl up-to-date:
  bazel-bin/tests/multi_repl/a/a@repl@repl
INFO: Elapsed time: 1.159s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 11 total actions
INFO: Build completed successfully, 11 total actions
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
Traceback (most recent call last):
  File "/home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/execroot/rules_haskell/bazel-out/host/bin/haskell/cc_wrapper-python", line 386, in <module>
    Main()
  File "/home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/execroot/rules_haskell/bazel-out/host/bin/haskell/cc_wrapper-python", line 286, in Main
    module_space = FindModuleSpace()
  File "/home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/execroot/rules_haskell/bazel-out/host/bin/haskell/cc_wrapper-python", line 117, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for /home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/execroot/rules_haskell/bazel-out/host/bin/haskell/cc_wrapper-python
`cc_wrapper-python' failed in phase `gcc'. (Exit code: 1)
```

Note: you will have to run `bazel clean` before because of a bug in bazel itself bazelbuild: https://github.com/bazelbuild/bazel/issues/12914

**Expected behavior**

I'd like to be able to run a repl with `--nobuild_runfile_links`. This feature is important for me because without it bazel is generating too much file (more than 25 millions) and kills our CI, see https://github.com/bazelbuild/bazel/issues/2951

**Environment**
 - OS name + version: nixos or ubuntu something
 - Bazel version: 3.3.1 or 4.0
 - Version of the rules: bf28f164772c2e70f4f64509006eb4f488f56681

**Additional context**

This is certainly related to #1312

**Comment by aherrmann** [comment] 2021-01-28 10:27
The error seems to come out of Bazel's [Python stub template](https://github.com/bazelbuild/bazel/blob/2e65a82a8ee01c15acb3acc99b16a499d8c4cc4e/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L117). The issue seems to be that, at that stage, it only looks for the `.runfiles` tree next to `argv[0]` but does not consider the `RUNFILES_DIR` env-var. I've patched the GHCi wrapper with
``` diff
diff --git a/haskell/private/ghci_repl_wrapper.sh b/haskell/private/ghci_repl_wrapper.sh
index 5b278304..03d8db69 100644
--- a/haskell/private/ghci_repl_wrapper.sh
+++ b/haskell/private/ghci_repl_wrapper.sh
@@ -59,4 +59,4 @@ ARGS=%{ARGS}

 # shellcheck disable=SC1083
 %{ENV}
-"$TOOL_LOCATION" "${ARGS[@]}" "$@"
+/usr/bin/strace -f -e trace=execve -s 2048 -v "$TOOL_LOCATION" "${ARGS[@]}" "$@"
```
to confirm that the correct `RUNFILES_DIR` is forwarded to the cc_wrapper. Indeed, the environment inclues
```
"RUNFILES_DIR=.../execroot/rules_haskell/bazel-out/k8-fastbuild/bin/tests/multi_repl/a/a@repl@repl.runfiles"
```
which includes cc_wrapper runfiles such as `rules_haskell/haskell/cc_wrapper.py`.

So, I think this is an upstream issue with Bazel's Python stub template. A way to test this may be to patch that stub template so that `FindModuleSpace` also checks for the `RUNFILES_DIR` env-var. A full description of what the runfiles mechanism should generally look like can be found [here](https://docs.google.com/document/d/e/2PACX-1vSDIrFnFvEYhKsCMdGdD40wZRBX3m3aZ5HhVj4CtHPmiXKDCxioTUbYsDydjKtFDAzER5eg7OjJWs3V/pub).

**Comment by avdv** [comment] 2023-11-28 12:53
Closing, as I cannot reproduce the problem anymore:
```console
$ cd rules_haskell_tests
$ bazel clean --expunge
$ bazel run --nobuild_runfile_links //tests/multi_repl/a:a@repl
Starting local Bazel server and connecting to it...
DEBUG: /root/.cache/bazel/_bazel_root/4e44c3743109bc8d0c5662725969652f/external/rules_haskell/haskell/private/versions.bzl:134:14: WARNING: Current Bazel version is 6.4.0; expected at most 6.3.2
...
INFO: Analyzed target //tests/multi_repl/a:a@repl (82 packages loaded, 11838 targets configured).
INFO: Found 1 target...
Target //tests/multi_repl/a:a@repl up-to-date:
  bazel-bin/tests/multi_repl/a/a@repl@repl
INFO: Elapsed time: 68.555s, Critical Path: 0.03s
INFO: 12 processes: 12 internal.
INFO: Build completed successfully, 12 total actions
INFO: Running command line: bazel-bin/tests/multi_repl/a/a@repl@repl
GHCi, version 9.6.2: https://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling A.A              ( tests/multi_repl/a/src/A/A.hs, interpreted )
Ok, one module loaded.
Loaded GHCi configuration from /root/.cache/bazel/_bazel_root/4e44c3743109bc8d0c5662725969652f/execroot/rules_haskell_tests//bazel-out/k8-fastbuild/bin/tests/multi_repl/a/ghci-repl-script-a@repl
ghci> 
```

**Closed by avdv** 2023-11-28 12:53 UTC
Labels: type: bug
