### ISSUE TITLE
CI should verify supported GHC versions

### ISSUE THREAD

**Issue by Xophmeister** [tweag/rules_haskell#1668] opened 2021-12-20 17:12 UTC
Our CI currently does not verify the different GHC versions that we attest are supported. This came to light by virtue of #1666, which fixes GHC 9.0.1 and 9.2.1 in `rules_haskell` that weren't caught by the current pipeline.

See https://github.com/matsubara0507/example-haskell-with-bazel for a prototype solution.

**Comment by GuillaumeGen** [comment] 2022-07-26 15:57
Duplicate of #458

**Closed by GuillaumeGen** 2022-07-26 15:57 UTC
Labels: duplicate, type: bug
