### ISSUE TITLE
Rules haskell remote caching

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1600] opened 2021-10-05 14:16 UTC
A question about remote caching.

In my latest project, I was using bazel remote caching to cache our build (including rules_haskell) and it was ok. Bazel caching is slow (because it needs to fetch all the intermediate artifacts), but with a fast internet connection, it was generally a bit faster than building everything locally. We also had a lot of C++ and AFAIK `gcc` produces reproducible binaries. Our hackage dependencies where built using nix, so this part of the caching was not handled by bazel.

I recently moved to a new codebase which is 100% haskell and uses `stack_snapshot` to build hackage dependencies.

And I observed that remote caching is totally unreliable. Sometimes it works, fetching our hackage dependencies in less than an hour, sometimes it fails, and we have to rebuild everything, which can take a few hours.

I traced different build using `--execution_log_json_file` and all the Haskell `.hi` files generated are different.

GHC status about it is a bit unclear: https://gitlab.haskell.org/ghc/ghc/-/issues/4012, it says that it won't be ready for 9.2 (btw, we are using 8.10), but there is also mentions that interfaces files are reproducible, but that's not what I'm observing.

On rules_haskell master:

```console
$ bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

[nix-shell:~/the_company/rules_haskell]$ bazel build @stackage//:primitive --execution_log_json_file=exec_log.json
INFO: Analyzed target @stackage//:primitive (54 packages loaded, 1245 targets configured).
INFO: Found 1 target...
Target @stackage//:primitive up-to-date:
  bazel-bin/external/stackage/primitive-0.7.1.0/_install/lib/libHSprimitive-0.7.1.0.a
  bazel-bin/external/stackage/primitive-0.7.1.0/_install/lib/libHSprimitive-0.7.1.0-ghc8.10.4.so
INFO: Elapsed time: 60.916s, Critical Path: 59.62s
INFO: 25 processes: 23 internal, 2 linux-sandbox.
INFO: Build completed successfully, 25 total actions

[nix-shell:~/the_company/rules_haskell]$ bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

[nix-shell:~/the_company/rules_haskell]$ bazel build @stackage//:primitive --execution_log_json_file=exec_log2.json
INFO: Analyzed target @stackage//:primitive (54 packages loaded, 1245 targets configured).
INFO: Found 1 target...
Target @stackage//:primitive up-to-date:
  bazel-bin/external/stackage/primitive-0.7.1.0/_install/lib/libHSprimitive-0.7.1.0.a
  bazel-bin/external/stackage/primitive-0.7.1.0/_install/lib/libHSprimitive-0.7.1.0-ghc8.10.4.so
INFO: Elapsed time: 59.611s, Critical Path: 58.51s
INFO: 25 processes: 23 internal, 2 linux-sandbox.
INFO: Build completed successfully, 25 total actions
```
```diff
[nix-shell:~/the_company/rules_haskell]$ diff exec_log.json exec_log2.json -C5
*** exec_log.json	2021-10-05 16:10:22.301866503 +0200
--- exec_log2.json	2021-10-05 16:13:45.727847132 +0200
***************
*** 3464,3650 ****
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Control/Monad/Primitive.dyn_hi",
      "digest": {
!       "hash": "70187bd1d9e6d59501817391119320aa53ffc0828c5276a927ae8ba70b0854e4",
        "sizeBytes": "55693",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Control/Monad/Primitive.hi",
      "digest": {
!       "hash": "762d97ffd8d2728401f2c36c5fa65c20b2cc1d5d8fd4b8e50a5eef2a10dc1e31",
        "sizeBytes": "55690",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Array.dyn_hi",
      "digest": {
!       "hash": "ad0a2fec449f9fb035b6027d886d91461daceb7ae212aa94a68a84389eaeabd5",
!       "sizeBytes": "110016",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Array.hi",
      "digest": {
!       "hash": "504af27133ad14abb60194b6e5d9a2b36d96bfad46ca00d96e80ca92dd9695c6",
!       "sizeBytes": "110013",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/ByteArray.dyn_hi",
      "digest": {
!       "hash": "9e9c22b6e31c94dc5f0435f2f08acd2e343cd336582e09fe8b99b620bf354585",
        "sizeBytes": "58304",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/ByteArray.hi",
      "digest": {
!       "hash": "00cb4d93a2bdc6bc2ed9c553c95d1bfd28068d089271435bb6dfbe585d3bf8e8",
        "sizeBytes": "58301",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Internal/Compat.dyn_hi",
      "digest": {
!       "hash": "0bb63291aab67f0cee1f03ea672b836c035f9730ebc700dc7f91d606dad90402",
        "sizeBytes": "1418",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Internal/Compat.hi",
      "digest": {
!       "hash": "794481aa50d6dfa69ff9f11f03aa0d0bd7e47427636496d86669ac040f6bfae2",
        "sizeBytes": "1415",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Internal/Operations.dyn_hi",
      "digest": {
!       "hash": "c663cce3f08b1ed1f7a1da973ae0096f7afd8cb3cced1aa3f2704edeb5c7592a",
!       "sizeBytes": "18498",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Internal/Operations.hi",
      "digest": {
!       "hash": "ce0f76d553bc71c3fe2fe315a3b4fa9574b3e379138f3222fe663a1c370a9320",
!       "sizeBytes": "18495",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MVar.dyn_hi",
      "digest": {
!       "hash": "abb75984dd89b576cd16dd9ad0e4157ebfcb3cdfb66cba6a82a8fcf05aeec1b4",
        "sizeBytes": "10200",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MVar.hi",
      "digest": {
!       "hash": "1c5964b21359b6e7ea84f50fc1c37f9e7e87904944311059a3629321c18cc2e3",
        "sizeBytes": "10197",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MachDeps.dyn_hi",
      "digest": {
!       "hash": "6b12874b7d0f3b7824234e69b4e67d039007aa42a27857be74a3f5429ded1a38",
!       "sizeBytes": "4097",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MachDeps.hi",
      "digest": {
!       "hash": "5ff694ed13f5460b79bcd63b3070d11b327f9811d6a8a5ed756d9e03212fb651",
!       "sizeBytes": "4094",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MutVar.dyn_hi",
      "digest": {
!       "hash": "c36c54d486fd36afea44461611de5b811e1a5efe90284d67de7675ec2d8fc02f",
        "sizeBytes": "7623",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MutVar.hi",
      "digest": {
!       "hash": "ac86ad51c91c6feb603b184c5d983c48497057d67b62baf78d728e116a8601be",
        "sizeBytes": "7620",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/PrimArray.dyn_hi",
      "digest": {
!       "hash": "79fb4ca6ca911872077d9dd8bd1b9526c022c93817c3c19620119fcf0788bfa4",
!       "sizeBytes": "111986",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/PrimArray.hi",
      "digest": {
!       "hash": "9d609513844104228dae7932b84cd47fa396d50ae8475019e12a726783ae6316",
!       "sizeBytes": "111983",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Ptr.dyn_hi",
      "digest": {
!       "hash": "f80d1deab83097dde841ba82bfd9ee119a042cd00e59f358f91dbf3b1fd0ce04",
        "sizeBytes": "11738",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Ptr.hi",
      "digest": {
!       "hash": "3ecf0e6d1b3cfe7b22a22c8a74028f38663c1585da88bcbfa7a7d1f0248ed52a",
        "sizeBytes": "11735",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/SmallArray.dyn_hi",
      "digest": {
!       "hash": "c5688c48254993d9ac927d71f7655d99073e06681fc30a024a4fb68e1a7e6b27",
!       "sizeBytes": "109653",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/SmallArray.hi",
      "digest": {
!       "hash": "bd82b3ae7ab061a11bc334d48f2d345030dd9644caa19f09a13379f7b85648db",
!       "sizeBytes": "109650",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Types.dyn_hi",
      "digest": {
!       "hash": "094eb7baa253cd7e0a8aa22a87d4ae63eb3df4f844d44707bf816737881d25ab",
        "sizeBytes": "141816",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Types.hi",
      "digest": {
!       "hash": "e3ff822d46bf6fc95cc5b4d4c81a9dc74498283b295d18d579e197b16f28d25d",
        "sizeBytes": "141813",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive.dyn_hi",
      "digest": {
!       "hash": "37fc3c8e820ad8eba1b45f22d4505556c6410d691ba9a6b774e3e9f4e778cd10",
!       "sizeBytes": "9860",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive.hi",
      "digest": {
!       "hash": "782c9e8710328579a03227679d18032259e6cf95c4bcb604796839ec374ccfdc",
!       "sizeBytes": "9857",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/include/primitive-memops.h",
      "digest": {
--- 3464,3650 ----
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Control/Monad/Primitive.dyn_hi",
      "digest": {
!       "hash": "e78d4a78a67704632edf740b1a371171d601eaf31da35208355e8a4e800edaf3",
        "sizeBytes": "55693",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Control/Monad/Primitive.hi",
      "digest": {
!       "hash": "96bf7348eea3b682e1e49f58f84dc03a9e0d4086f8891738da0153680f9048fb",
        "sizeBytes": "55690",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Array.dyn_hi",
      "digest": {
!       "hash": "56fb6d7278fda0bb10750aef10272c7a6846a8616848f68b1527db25966b23da",
!       "sizeBytes": "110017",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Array.hi",
      "digest": {
!       "hash": "b0c9e2c817b68339a8985f14c1e71a280806ed503079241186ae4e843c7e9fb4",
!       "sizeBytes": "110014",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/ByteArray.dyn_hi",
      "digest": {
!       "hash": "bd6c5df0c883f82d14954636b765b603d9988c87c4e17d938f8545f264004c6e",
        "sizeBytes": "58304",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/ByteArray.hi",
      "digest": {
!       "hash": "90c213b1d264a81f820ae1844823cf21094d217f0c43ffacde77675fc0e78401",
        "sizeBytes": "58301",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Internal/Compat.dyn_hi",
      "digest": {
!       "hash": "179861924f51b25198c05d5222b1d3cd04d1cbc2f358483c010da81222ed7318",
        "sizeBytes": "1418",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Internal/Compat.hi",
      "digest": {
!       "hash": "898d5997b8444f657d013a52512e2e2b19f6ab82944d8f5307f4926ff6f9bbea",
        "sizeBytes": "1415",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Internal/Operations.dyn_hi",
      "digest": {
!       "hash": "7836df0ae3fdd52f59e7bced53a77d3b9f1e64f439a16238e54502366c4360ac",
!       "sizeBytes": "18497",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Internal/Operations.hi",
      "digest": {
!       "hash": "9317bd2d64872f05339ce086f09f59b07e26a84e042331082bb2e10dfd12e923",
!       "sizeBytes": "18494",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MVar.dyn_hi",
      "digest": {
!       "hash": "74c015d27b20f36140e7685df3e9b0a9ead6ad5ab94003235a5e17da323493b4",
        "sizeBytes": "10200",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MVar.hi",
      "digest": {
!       "hash": "f0f10ad97762ccdfee23b2c4d7b33cd18adaa560d10c7237291373fe94965235",
        "sizeBytes": "10197",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MachDeps.dyn_hi",
      "digest": {
!       "hash": "829adf036f02eba42e34e157e5e1817cdf948aa60e4456cd8903fc4d85535ff2",
!       "sizeBytes": "4098",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MachDeps.hi",
      "digest": {
!       "hash": "d2c666f2fefbe3191778269afa6c731064d11e55c895a69acd0fa7910a1f56af",
!       "sizeBytes": "4095",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MutVar.dyn_hi",
      "digest": {
!       "hash": "bb484b901431faf14ccdbea1df74bd329c550bd7d73f3fa3b1c7cdb56104daab",
        "sizeBytes": "7623",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/MutVar.hi",
      "digest": {
!       "hash": "88caf238bcfc7f35049fa7a290e8b5541ec7b33a63054d334d543f4936285627",
        "sizeBytes": "7620",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/PrimArray.dyn_hi",
      "digest": {
!       "hash": "3ef943611adfacba5b53c324a04643a8f6e4ba42133da65cbf4a9457ef2ca5aa",
!       "sizeBytes": "111985",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/PrimArray.hi",
      "digest": {
!       "hash": "4e05cfd9d7c648c82106f2da7333f0405bf5bee7f11103fa23b0ea3bc67ca6d8",
!       "sizeBytes": "111982",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Ptr.dyn_hi",
      "digest": {
!       "hash": "1702600d15297065c83c0d626aa90891bfec9944cae8c19132c40808d298cc38",
        "sizeBytes": "11738",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Ptr.hi",
      "digest": {
!       "hash": "e5d7c8ed9767b49df4eae9f7c8614219d0a9ac73947eb27dcf1b4730de4f4254",
        "sizeBytes": "11735",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/SmallArray.dyn_hi",
      "digest": {
!       "hash": "58b87cd14a3f0b8952deb1e993a2c25dd07f9da30ff3101cdccdd99feaf14a39",
!       "sizeBytes": "109654",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/SmallArray.hi",
      "digest": {
!       "hash": "eda0745db43703b37685d0918f46150c855da2dff79d2c2d15be6e36e467622e",
!       "sizeBytes": "109651",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Types.dyn_hi",
      "digest": {
!       "hash": "960ce8dcfdc5ab665c7e510bd5f010d3b099918575455a16111d84447853ae06",
        "sizeBytes": "141816",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive/Types.hi",
      "digest": {
!       "hash": "efecf1a93a58c6f5e4c7a813b9892cc813246d6ac0a2d1c384c376d3bf145ada",
        "sizeBytes": "141813",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive.dyn_hi",
      "digest": {
!       "hash": "ca2ee99557890127da1f3d19d989869d82b41da32a60e2d7c8f7e591b7f2bff4",
!       "sizeBytes": "9858",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/Data/Primitive.hi",
      "digest": {
!       "hash": "8864ff0722a191b5797e9cd6a4bedc0a65154cac39b54e0ab3803cd862e950a8",
!       "sizeBytes": "9855",
        "hashFunctionName": "SHA-256"
      }
    }, {
      "path": "bazel-out/k8-fastbuild/bin/external/stackage/primitive-0.7.1.0/_install/primitive-0.7.1.0_iface/include/primitive-memops.h",
      "digest": {
```

In this context, bazel is unable to remote cache any build.

I cannot reproduce this using GHC alone (i.e. multiples run of the same `cabal build` on a project leads to the same interface files).

What I have done wrong?

**Comment by aherrmann** [comment] 2021-11-12 17:23
Regarding the non-reproducible interface files. I've debugged this on a minimal example `haskell_cabal_library` target. Looking at the difference between two intances of the generated `.hi` file with the help of `ghc --show-iface` I see the following diff:
```
--- /dev/fd/63  2021-11-12 18:16:20.295236371 +0100
+++ /dev/fd/62  2021-11-12 18:16:20.295236371 +0100
@@ -9,7 +9,7 @@
   ABI hash: 12838d23bdf42e004cde35d79cea08f4
   export-list hash: 96dd08fd9dd9e3e2d0f987b4bf9de728
   orphan hash: 693e9af84d3dfcc71e640e005bdc5e2e
-  flag hash: 27743312d2ec1339ae255c3fc7fdf6d7
+  flag hash: 374ae2938af662df5da374a6187f9af6
   opt_hash: cb09a535710eb16767a299f2ded44a31
   hpc_hash: 93b885adfe0da089cdf634904fd59f71
   plugin_hash: ad164012d6b1e14942349d58b1132007
```
Meaning the difference lies in the `flag hash` field. This is a hash of the `DynFlags` calculated by `fingerprintDynFlags` used for recompilation avoidance.

The issue seems to be that the Cabal rules [create a temporary directory](https://github.com/tweag/rules_haskell/blob/9fbdb5e6b85813b705ae15ff98f77968465fea6d/haskell/private/cabal_wrapper.py#L160) for the build's `distdir`. The name of that temporary directory is non-deterministic and it makes its way into some of the flags passed to GHC. Using a fixed `distdir` removes the non-determinism on the interface files, at least in the minimal repro.

**Comment by aherrmann** [comment] 2021-12-02 15:33
@1648 addresses the non-reproducible interface files aspect for Cabal libraries without Bazel built C library dependencies.

**Comment by aherrmann** [comment] 2022-02-08 09:11
#1689 addresses the non-reproducible interface files aspect for Cabal libraries with or without C library dependencies.
With #1648 and #1689 `haskell_cabal_library|binary` should be deterministic, provided that GHC and the Cabal package itself are deterministic.

The unexpected rebuild aspect is not addressed. However, I was not able to reproduce it and can't debug it further without more information. @guibou I'll close this for now. Feel free to reopen if you have more information on why the package was rebuilt unexpectedly or a way to reproduce it.

**Closed by aherrmann** 2022-02-08 09:11 UTC
Labels: type: bug

**Comment by guibou** [comment] 2022-02-08 10:46
Well done. Happy to see progress here!

Sorry, I'm not using `stack_snapshot` anymore, so I don't have much more information available. I'm ok with this bug being closed.
