### ISSUE TITLE
REPL scripts do not work with ghcid

### ISSUE THREAD

**Issue by gdeest** [tweag/rules_haskell#330] opened 2018-07-10 13:52 UTC
I tried using `ghcid` in combination with the REPL scripts generated by Bazel in order to get some interactive feedback on my changes.

Here is how it goes:

```
[nix-shell:~/code/project]$ ghcid --command ./bazel-bin/project-repl 
Loading ./bazel-bin/project-repl ...
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help

No files loaded, GHCi is not working properly.
Command: ./bazel-bin/project/numero-repl
```

It looks like `ghcid` relies on all target modules being loaded upon ghci startup, which is not the case with those scripts (modules must be manually loaded with `:load`). Is there a way to make this work ?

**Comment by judah** [comment] 2018-07-10 17:01
A user reported yesterday that they got ghcid working via:
```
ghcid --command "bazel run --direct_run //haskell/platform-effect:platform-effect-repl"
```
I haven't had the chance to try it myself, though.

**Comment by mboes** [comment] 2018-12-02 17:38
@gdeest are you still able to reproduce?

**Comment by dajmaki** [comment] 2018-12-11 09:10
This worked for me with following command:
```
ghcid -c "bazel run --direct_run //some/library:target@repl"
```

**Comment by mboes** [comment] 2019-04-06 08:53
Closing, since @gdeest did not reply to https://github.com/tweag/rules_haskell/issues/330#issuecomment-443525602 and there subsequently was a report of success. Reopen if this is still an issue.

**Closed by mboes** 2019-04-06 08:53 UTC
Labels: type: feature request
