### ISSUE TITLE
haddock can't link to prebuild packages

### ISSUE THREAD

**Issue by regnat** [tweag/rules_haskell#901] opened 2019-05-27 06:00 UTC
**Describe the bug**

When building the docs for a package, haddock can't link to any identifier in prebuilt packages:

> Warning: LibB: could not find link destinations for:
    Int String

and the links indeed don't show up on the html doc:

![image](https://user-images.githubusercontent.com/7226587/58398182-77fa2080-8054-11e9-8e14-82b9dcfed4ae.png)

**To Reproduce**

```sh
bazel build //tests/haddock:haddock-transitive
firefox bazel-bin/tests/haddock/haddock-transitive/testsZShaddockZShaddock-lib-b/LibB.html
```

Check that the `Int` or `String` types in the signatures aren't links.

**Expected behavior**

The generated documentation should contain links to `Int` or `String` from the standard library

**Environment**
- NixOS 19.09.git.c713d03 
- bazel 0.24.0 (from the project's shell.nix)
- rules_haskell at 9ba36c36c856cc0a196c9bb4573b3aaa4e8cf5b0 (current master)

**Additional context**

Might be a regression introduced by https://github.com/tweag/rules_haskell/pull/859 since this changes the way we handle prebuilt dependencies

**Comment by guibou** [comment] 2019-06-05 14:22
I confirm that the regression is introduced by #859, I bisected it.

**Comment by guibou** [comment] 2019-06-05 14:50
haddock had never fully worked on a codebase I'm managing, even before #859. I suspect that the haddock informations for transitive dependencies were not correctly propagated.

I'm assigning this issue to myself because repairing haddock is a mandatory step before fixing the specific haddock issue I'm facing.

**Comment by guibou** [comment] 2019-06-06 16:49
#928 will close this issue. I no longer observing the missing links in the `//tests/haddock/...` samples.

However, there is still some haddock warnings during the generation of protobuff rules. I don't know their origin for now, we'll open another issue if that's a problem.

**Comment by Profpatsch** [comment] 2019-06-11 13:06
Huh, #928 was merged but this issue didn’t autoclose.

**Closed by Profpatsch** 2019-06-11 13:06 UTC
Labels: type: bug
