### ISSUE TITLE
Dependency specified by Stack snapshot looks in the wrong folder for Cabal data-files

### ISSUE THREAD

**Issue by patrickt** [tweag/rules_haskell#1335] opened 2020-05-19 18:02 UTC
**Describe the bug**
I’m attempting to build [this project](https://github.com/github/semantic/tree/bazel-experiments/semantic-ruby) with Bazel + rules_haskell. Said project depends on [this file in the `tree-sitter-ruby` dependency](https://github.com/tree-sitter/tree-sitter-ruby/blob/eb2b6225bfb80010f2e4cbd27db8c6f3775230b5/src/node-types.json), which is specified in `tree-sitter-ruby`’s .cabal file in a `data-files` clause, and [exposed using a call](https://github.com/tree-sitter/haskell-tree-sitter/blob/master/tree-sitter-ruby/TreeSitter/Ruby.hs#L14) to `getDataFilePath`, from a generated `Paths_` file. I import the `tree-sitter-ruby` project via a Cabal snapshot specifying a Hackage version to use (`tree-sitter-ruby` is not on Hackage).

When I call the `getNodeTypesPath` that invokes `getDataFileName`, it yields an incorrect filename:

```
/private/var/tmp/_bazel_patrickt/9ab2276bd7abbc23224fda87a0d88539/external/rules_haskell_ghc_darwin_amd64/lib/tree-sitter-ruby-0.5.0.2_data/vendor/tree-sitter-ruby/src/node-types.json
```

The `tree-sitter-ruby-0.5.0.2_data` folder does not exist, and as such this lookup fails. This `node-types.json` file is present in the `bazel-*` directories created by the build process, and in the temporary cache.

```
~/s/semantic (bazel-experiments|●1✚1) $ fd "node-types" ./bazel*
bazel-bin/external/stackage/tree-sitter-python-0.9.0.2/_install/tree-sitter-python-0.9.0.2_data/vendor/tree-sitter-python/src/node-types.json
bazel-bin/external/stackage/tree-sitter-ruby-0.5.0.2/_install/tree-sitter-ruby-0.5.0.2_data/vendor/tree-sitter-ruby/src/node-types.json
bazel-out/darwin-fastbuild/bin/external/stackage/tree-sitter-python-0.9.0.2/_install/tree-sitter-python-0.9.0.2_data/vendor/tree-sitter-python/src/node-types.json
bazel-out/darwin-fastbuild/bin/external/stackage/tree-sitter-ruby-0.5.0.2/_install/tree-sitter-ruby-0.5.0.2_data/vendor/tree-sitter-ruby/src/node-types.json
bazel-semantic/bazel-out/darwin-fastbuild/bin/external/stackage/tree-sitter-python-0.9.0.2/_install/tree-sitter-python-0.9.0.2_data/vendor/tree-sitter-python/src/node-types.json
bazel-semantic/bazel-out/darwin-fastbuild/bin/external/stackage/tree-sitter-ruby-0.5.0.2/_install/tree-sitter-ruby-0.5.0.2_data/vendor/tree-sitter-ruby/src/node-types.json
```

I notice that the files are in an `external/stackage` folder, rather than in `external/rules_haskell_ghc_darwin_amd64/lib`: could that be the associated issue?

**To Reproduce**
Steps to reproduce the behavior.

1. Check out github.com/github/semantic
2. Switch to the `bazel-experiments` branch
3. `bazel build //semantic-ruby:lib`
4. Observe build failure in `Language.Ruby.AST`.

**Expected behavior**
The result of functions that call `getDataFilePath` should point to valid file locations.

**Environment**
 - OS name + version: macOS Catalina
 - Bazel version: bazel 3.1.0
 - Version of the rules: 0.12

**Comment by aherrmann** [comment] 2020-05-20 09:14
Thank you for reporting this.

> I notice that the files are in an `external/stackage` folder, rather than in `external/rules_haskell_ghc_darwin_amd64/lib`: could that be the associated issue?

That is indeed the issue. This is a duplicate of https://github.com/tweag/rules_haskell/issues/1246 and unfortunately an upstream issue in Cabal: https://github.com/haskell/cabal/issues/6549. As pointed out in #1246 this can be worked around by embedding the data files in the package where they originate using `file-embed`. See [here](https://github.com/digital-asset/daml/blob/2af134ca69c090baab31c255762ce30846da0c18/bazel_tools/haskell-js-jquery.patch) for an example, that particular patch works around the issue for `js-jquery`.

Closing as duplicate, though please do let us know if you have further questions on the issue.

**Closed by aherrmann** 2020-05-20 09:14 UTC
Labels: type: bug
