### ISSUE TITLE
`stack_snapshot` get invalidated too often

### ISSUE THREAD

**Issue by regnat** [tweag/rules_haskell#1096] opened 2019-09-12 09:47 UTC
**Describe the bug**

Dependencies built with `stack_packages` or `haskell_cabal_package` gets
invalidated at least each time the `PATH` changes due to the use of
`use_default_shell_env`.

**To Reproduce**

From the `examples` directory:

```sh
# Build a random cabal package
nix-shell --pure --run "bazel build @stackage//:random"
# Rebuild it again and see that it's cached
nix-shell --pure --run "bazel build @stackage//:random"
# Add `hello` to the `buildInputs` list in `shell.nix`
# Rebuild the random package and see that it isn't cached anymore
nix-shell --pure --run "bazel build @stackage//:random"
```

**Expected behavior**

A change in the environment shouldn't trigger a cache miss.

**Environment**
 - OS name + version: nixos unstable
 - Bazel version: 0.28.0 (from the example's shell.nix)
 - Version of the rules: latest master (79e2c5316bef9873f6d6a155f1f14f3d3ae39967)

**Comment by mboes** [comment] 2019-09-23 12:38
Did you mean `stack_snapshot`?

**Comment by regnat** [comment] 2019-09-25 05:15
> Did you mean `stack_snapshot`?

Oh yes, sorry, I'll update the title

**Comment by mboes** [comment] 2019-09-25 07:28
> each time the PATH changes due to the use of use_default_shell_env.

This is a side-effect of not having a shell toolchain. Cabal assumes quite a bit from the environment (in terms of available commands).

**Comment by jkachmar** [comment] 2019-10-29 22:02
Should #1097 and #1117 (which have since been merged) automatically address the problem, and should this issue be closed accordingly?

Or is there a need for some sort of regression test to make sure `stack_snapshot` dependencies are always cached?

**Comment by aherrmann** [comment] 2019-10-30 09:39
This should be fixed now. I've verified that the following does not cause a rebuild, while it did before those PRs were merged.
```
$ nix-shell --pure --run 'bazel build @stackage//:void'
$ nix-shell --pure --run 'PATH=foo:$PATH bazel build @stackage//:void'
```

**Closed by aherrmann** 2019-10-30 09:39 UTC
