### ISSUE TITLE
Protobuf generated module conflicts with proto-lens

### ISSUE THREAD

**Issue by jpgneves** [tweag/rules_haskell#1111] opened 2019-10-01 07:53 UTC
**Describe the bug**
Some protobuf files import `google/protobuf/descriptor.proto`, such that for a `proto_library` target for such a file to build, I have to include `@com_google_protobuf//:descriptor_proto` dependency.

However, `proto-lens` already includes a module with the same name generated from similar definitions, which results in an ambiguous module name error:

```
   Ambiguous module name `Proto.Google.Protobuf.Descriptor':
     it was found in multiple packages:
       descriptor-proto proto-lens-0.4.0.1
   |
25 | import qualified Proto.Google.Protobuf.Descriptor
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Example of a file I'm attempting to generate Haskell from: https://github.com/googleforgames/open-match/blob/master/third_party/google/api/annotations.proto#L20

I've filed an issue with `proto-lens` (https://github.com/google/proto-lens/issues/344), and they suggest `rules_haskell` might be a better place to fix the clash, as a suggested option would be that maybe `rules_haskell` could provide the required `.proto` files, as `proto-lens` does itself: https://github.com/google/proto-lens/blob/5e5bec02a4193d0a0d797da3551fc0893adb836e/proto-lens/package.yaml#L27

**To Reproduce**
Create a `.proto` file which has a dependency on `google/protobuf/descriptor.proto`:

```
package foo;

import "google/protobuf/descriptor.proto";
```

Create a `BUILD.bazel` file using `rules_haskell` with appropriate targets:

```
load("@rules_haskell//haskell:protobuf.bzl",
     "haskell_proto_library",
     "haskell_proto_toolchain",
)

haskell_proto_toolchain(
    name = "protobuf-toolchain",
    protoc = "@com_google_protobuf//:protoc",
    plugin = "@proto-lens-protoc//:bin/proto-lens-protoc",
    deps = [
        "@stackage//:base",
        "@stackage//:bytestring",
        "@stackage//:containers",
        "@stackage//:data-default-class",
        "@stackage//:deepseq",
        "@stackage//:lens-family",
        "@stackage//:lens-labels",
        "@stackage//:proto-lens",
        "@stackage//:text",
    ],
)

proto_library(
     name = "foo",
     srcs = ["foo.proto"],
     deps = [ "@com_google_protobuf//:descriptor_proto" ],
)

haskell_proto_library(
    name = "foo_haskell",
    deps = [
        ":foo",
    ],
)
```

Build the `foo_haskell` target.

**Expected behavior**
The generated Haskell library compiles successfully.

**Environment**
 - OS name + version: NixOS 19.03
 - Bazel version: 0.29.0
 - Version of the rules: 0.10

**Additional context**
This would be an issue in other repositories that already have `proto_library` definitions depending on `@com_google_protobuf//:descriptor_proto`, such as https://github.com/googleapis/googleapis/blob/master/google/api/BUILD.bazel#L12

**Comment by judah** [comment] 2019-10-29 21:13
Following up, I believe the issue is resolved (or, at least, resolvable) now that proto-lens-0.6 has been released.  In the new release, the descriptor protos were moved out of the main "proto-lens" package, so it should be compatible with a proto_library rule that wraps descriptor_proto as in the above example.  I don't have a good way of immediately testing it myself with rules_haskell, though.

**Comment by jpgneves** [comment] 2019-11-01 13:38
Thanks for the follow up, I'll give it a try shortly and let you know, but it does look promising!

**Comment by hanshoglund** [comment] 2020-06-16 13:29
@jpgneves I believe #1369 (when merged) proves this is no longer an issue so this can be closed. Or is there anything else outstanding from your point of view?

**Closed** 2020-06-19 14:44 UTC
Labels: type: bug
